"""dimensions

Revision ID: 1c9c1ba03936
Revises: 29a1b91f5335
Create Date: 2015-03-23 21:21:50.369398

"""

# revision identifiers, used by Alembic.
revision = '1c9c1ba03936'
down_revision = '29a1b91f5335'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appearance', sa.Column('position_x', sa.Integer(), nullable=False))
    op.add_column('appearance', sa.Column('position_y', sa.Integer(), nullable=False))
    op.add_column('appearance', sa.Column('size_x', sa.Integer(), nullable=False))
    op.add_column('appearance', sa.Column('size_y', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appearance', 'size_y')
    op.drop_column('appearance', 'size_x')
    op.drop_column('appearance', 'position_y')
    op.drop_column('appearance', 'position_x')
    ### end Alembic commands ###
