"""init

Revision ID: 29a1b91f5335
Revises: None
Create Date: 2015-03-21 22:37:34.783278

"""

# revision identifiers, used by Alembic.
revision = '29a1b91f5335'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('file_tag',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.create_table('thing_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('tag_id', 'thing_id')
    )
    op.create_table('appearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearance_tag',
    sa.Column('appearance_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_anti_tag', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['appearance_id'], ['appearance.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('appearance_id', 'tag_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appearance_tag')
    op.drop_table('appearance')
    op.drop_table('thing_tag')
    op.drop_table('file_tag')
    op.drop_table('file')
    op.drop_table('thing')
    op.drop_table('tag')
    ### end Alembic commands ###
