"""first

Revision ID: 320c06fc4460
Revises: None
Create Date: 2015-03-20 23:39:08.134433

"""

# revision identifiers, used by Alembic.
revision = '320c06fc4460'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_character',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'character_id')
    )
    op.create_table('file_tag',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.create_table('file_character_tag',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id', 'character_id')
    )
    op.create_table('character_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('tag_id', 'character_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_tag')
    op.drop_table('file_character_tag')
    op.drop_table('file_tag')
    op.drop_table('file_character')
    op.drop_table('character')
    op.drop_table('file')
    op.drop_table('tag')
    ### end Alembic commands ###
