"""source

Revision ID: 3ede87378463
Revises: 984412fc765
Create Date: 2015-03-25 00:08:35.966388

"""

# revision identifiers, used by Alembic.
revision = '3ede87378463'
down_revision = '984412fc765'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source')
    ### end Alembic commands ###
