"""comments

Revision ID: 404c68941de0
Revises: 4e0bdc6c755c
Create Date: 2015-04-07 22:11:17.579830

"""

# revision identifiers, used by Alembic.
revision = '404c68941de0'
down_revision = '4e0bdc6c755c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###
