"""anti_tags

Revision ID: 469e06179df0
Revises: 46a73667570
Create Date: 2015-03-21 18:07:29.266942

"""

# revision identifiers, used by Alembic.
revision = '469e06179df0'
down_revision = '46a73667570'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_thing_tag', sa.Column('is_anti_tag', sa.Boolean(), server_default='f', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_thing_tag', 'is_anti_tag')
    ### end Alembic commands ###
