"""init

Revision ID: 46a73667570
Revises: None
Create Date: 2015-03-21 11:23:38.890142

"""

# revision identifiers, used by Alembic.
revision = '46a73667570'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thing_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('tag_id', 'thing_id')
    )
    op.create_table('file_thing',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'thing_id')
    )
    op.create_table('file_thing_tag',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id', 'thing_id')
    )
    op.create_table('file_tag',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_tag')
    op.drop_table('file_thing_tag')
    op.drop_table('file_thing')
    op.drop_table('thing_tag')
    op.drop_table('tag')
    op.drop_table('file')
    op.drop_table('thing')
    ### end Alembic commands ###
