"""roles like artist and commissioner

Revision ID: 4e0bdc6c755c
Revises: 3ede87378463
Create Date: 2015-03-27 21:29:16.599912

"""

# revision identifiers, used by Alembic.
revision = '4e0bdc6c755c'
down_revision = '3ede87378463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    thing_role = op.create_table('thing_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_thing_role',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['role_id'], ['thing_role.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('file_id', 'thing_id', 'role_id')
    )
    op.alter_column(u'tag', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'thing', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.bulk_insert(thing_role, [
      dict(
        id=1,
        name='artist',
      ),
      dict(
        id=2,
        name='recipient',
      ),
    ])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'thing', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'tag', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('file_thing_role')
    op.drop_table('thing_role')
    ### end Alembic commands ###
