"""created at

Revision ID: 979cbcd1a94
Revises: 404c68941de0
Create Date: 2015-04-07 22:50:43.208952

"""

# revision identifiers, used by Alembic.
revision = '979cbcd1a94'
down_revision = '404c68941de0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.arrow

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), server_default=sa.text(u"timezone('utc',now())"), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_at')
    ### end Alembic commands ###
