"""changed field name

Revision ID: 984412fc765
Revises: 1c9c1ba03936
Create Date: 2015-03-23 21:49:18.180611

"""

# revision identifiers, used by Alembic.
revision = '984412fc765'
down_revision = '1c9c1ba03936'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appearance_tag', 'is_anti_tag', new_column_name='negative')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appearance_tag', 'negative', new_column_name='is_anti_tag')
    ### end Alembic commands ###
